twitter: account_tag for nick and channel
bitlbee/bitlbee pull request #147
Opened 2020-05-12 00:43 UTC by Thaodan

- twitter account is accessible now either under <account_tag> nickname or through #<account_tag> channel
- in contrast to status quo (twitter_<handle> / #twitter_<handle>) it  enables user to have a consistent namings, configurable by setting
   particular twitter account's tag
Avoid sending pings every time a new message is send in the twitter channel and only when the nick is nickname is mentioned.

Credit goes to @mkoskar (https://bugs.bitlbee.org/ticket/1173).
Rebased on current git

2020-05-12 10:49 UTC, dequis commented
As I wrote there:

>While the idea behind the patch is good, there should be some way to keep previously added accounts under the old style channel names. Not entirely sure how, other than making this behavior optional under a setting. 

To reply to your comment:

> Maybe set the default tag of the twitter account to tag_<handle>? 

Changing the account's tag is a UX breaking change too.

2022-07-15 17:30 UTC, Thaodan commented
I'm looking into this patch again to have it ready for merging.

I wonder important it is that things stay the same since this would imply that both behavior would need to stay.

Setting the tag to the <nick> for twitter accounts  for new accounts would be a middle ground that doesn't break existing UX.

2023-02-11 17:16 UTC, jelmer requested changes
please also rebase to enable github actions

2023-02-11 19:11 UTC, Thaodan commented
Rebased.

2024-06-21 14:54 UTC, jelmer commented
- Sorry, this just dropped off my radar

2024-06-21 19:41 UTC, Thaodan commented
Twitter support isn't working and as far as I know 3rd-party clients are against Twitter TOS.
Should we keep working on Twitter support?

2024-06-22 07:44 UTC, jelmer commented
Ah, right

2024-06-22 07:45 UTC, closed without merging