Modernize texts
bitlbee/bitlbee pull request #181
Opened 2023-04-04 18:01 UTC by robert-scheck

…there is no more ICQ, MSN or AIM support in BitlBee

2023-04-05 23:37 UTC, jelmer requested changes

2023-04-06 07:38 UTC, robert-scheck commented on doc/user-guide/Installation.xml
> +replaced by the version number of the BitlBee you downloaded (e.g. 3.6).
I know, but 0.91 is _very_ old now. So I thought a recent version makes sense for the next 10+ years.

2023-04-22 18:10 UTC, robert-scheck commented on doc/README
>  We are both console lovers. But it is annoying to have a few tty's open with
Given I changed this…is the new variant fine? Or would it be more acceptable if I skip this part completely?

2023-04-22 18:40 UTC, jelmer commented on doc/README
>  We are both console lovers. But it is annoying to have a few tty's open with
I'll defer to @Wilm0r as the original author

2023-06-11 17:28 UTC, robert-scheck commented
@Wilm0r, kind ping?

2023-06-12 10:55 UTC, Wilm0r commented
Yep, all seems reasonable to me, sorry for the delay!

2023-06-12 10:55 UTC, merged